### ISSUE TITLE
Highlight mouse click in video lessons

### ISSUE THREAD

**Issue by andreicoval** [rodislav/Mister_JavaBean_Lessons#1]
It's not clear when you perform click on important buttons inside IDE

**Comment by rodislav** [comment]
@andreicoval, please check the implementation in this video
https://www.youtube.com/watch?v=1Ao2pZCpnCw&index=3&list=PLPkoWZmDIKwCvNeBpZMejx8gQhglUxw-w

if this works, mark close it

**Comment by andreicoval** [comment]
It's not the best solution, but if there is not a better one, than we can go ahead with it

**Comment by rodislav** [comment]
yeah, I know.. still investigating to find a better one

**Comment by rodislav** [comment]
I think we are going to use this aproach: https://youtu.be/JIm4oMb9hQ8
