### ISSUE TITLE
Review :: Java, details about platform, tools

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#14]
review the content from google drive for the java chapter
https://docs.google.com/document/d/1Vu-EXPQXoL7Qljh8mAEcsXK5HOG-tS2mizUrq21H0wQ

**Comment by andreicoval** [comment]
All described in a very clear manner. It create a big picture of the main terms, which makes more easy to understand when we start read the full topic at provided links.
