### ISSUE TITLE
create standard image for video thumbnails where only the title will change

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#22]
this image will be used as custom thumbnail for all videos on youtuve for mister javabean, and the design should give a white spaces somewhere closer to center to put custom text for each topic

the text should be big so it's readable even when it's small on youtube page

**Comment by marrynelax** [comment]
attached you find an exemple of one template which I propose to use for all video on youtube for mister javabean

**black.jpg** - template shown on a dark screen exemple
**white.jpg** - template shown on a bright screen exemple 
**template.jpg** - the image ready to use
![black](https://cloud.githubusercontent.com/assets/20436134/23798977/22398e62-05a7-11e7-9a84-30d0ab1400f2.jpg)
![white](https://cloud.githubusercontent.com/assets/20436134/23798982/28b23bb8-05a7-11e7-8902-42ab31a4690b.jpg)
![template](https://cloud.githubusercontent.com/assets/20436134/23798996/3dac9158-05a7-11e7-8448-3bb8422d1f70.png)

**Comment by marrynelax** [comment]
fonts used for this template:

- Qanelas (Black) - first line;
- Qanelas (Regular) - second line;

[Qanelas.zip](https://github.com/rodislav/Mister_JavaBean_Lessons/files/834203/Qanelas.zip)

**Comment by rodislav** [comment]
please use only white background and put acces on the logo and title of the video

**Comment by marrynelax** [comment]
I propose 3 new exemples of the youtube template.

Simulation of them on youtube page :

![simulation1](https://cloud.githubusercontent.com/assets/20436134/24253739/6dd55452-0fe1-11e7-8581-6cc8bc5d38a7.png)
![simulation2](https://cloud.githubusercontent.com/assets/20436134/24253741/6dd7d5ce-0fe1-11e7-8ef4-25dc89f4d1d3.png)
![simulation3](https://cloud.githubusercontent.com/assets/20436134/24253740/6dd63340-0fe1-11e7-8878-e2020c7d6c17.png)

3 different tamplates  format 1280 x 720:

![template1](https://cloud.githubusercontent.com/assets/20436134/24254012/1d832000-0fe2-11e7-9ed2-923ebbbd805b.png)
![template_2](https://cloud.githubusercontent.com/assets/20436134/24254059/35b982fe-0fe2-11e7-9d8e-dfaf3ed97a5c.png)
![template_3](https://cloud.githubusercontent.com/assets/20436134/24254079/41d1f3be-0fe2-11e7-82e6-a877b9bf6861.png)
