### ISSUE TITLE
Please review J.2 1 of 15 - skeleton app

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#31]
https://www.youtube.com/watch?v=Utoyp75fXJw

**Comment by andreicoval** [comment]
This video starts with a UML diagram. As the UML wasn't covered before in this training material, I suggest to add in documentation at least the basics elements you use in this diagram: 
- I-interface, C-class and A-abstract class;
- what each type of arrows represent: one class implements an interface, another class extends a class, in particular is interesting to see the link between interface "ContactsRepository" and class "ContactsService";
- why abstract class doesn't have any connections to the main diagram;
In addition the terms "abstract class", "interface and method overriding" weren't covered until this stage and I suggest to make a short description in documentation. 
Also you can add some more information on Inheritance as we didn't cover it yet.

After a good understanding of diagram, the code wrote in this video become easy to understand.
- the way you created packages and grouped over there classes is clear, but a short description on each package in documentation will help;
- the Setters and Getters are clear, but a small comment on it will help;
- the changes you've made at the end to .puml file, which was reflected also in .svg file, are not easy to follow and require additional comments in documentation.

**Comment by rodislav** [comment]
I've added more details to the docs, this should be better now, yet, I've not covered all the parts with docs in the code, since this part should be studied rather than just looked, the links to the articles from the docs will explain all touched subjects
