### ISSUE TITLE
Review - Video for Functions

### ISSUE THREAD

**Issue by rodislav** [rodislav/Mister_JavaBean_Lessons#6]

**Comment by rodislav** [comment]
the video can be found here: https://www.youtube.com/watch?v=_kbJhpKNBa0&feature=youtu.be

**Comment by andreicoval** [comment]
Comments:
4m37s: rows 6 - I can't understand how it appears in parenthesis (magicianName: "David Blane"). It doesn't appear at my side, it appears only the parameter "David Blane". Is this important or could be ignored?
5m59s you clicked "Step Into", what's the difference beteen it and "Step Over"

- the typing speed is quite big, but when I get used with your style and also using the pause in youtube videos, I can follow you and I can understand almost everything. In order for videos to be much more easier to be understood by the public , you need to improve the balance betwwen the speed of writing and the perfect timings for micro-breaks (pause) in video editing.
- the english orthography still remains an issue to be improved.
- perhaps you can do new revised videos with a clean product at the end...

**Comment by rodislav** [comment]
for the "magicianName", there is a feature in newest versions of Idea - Parameter hinting: http://stackoverflow.com/a/39787499
and : https://blog.jetbrains.com/idea/2016/09/intellij-idea-2016-3-eap-faster-git-log-parameter-hints-and-more/   -   Parameter hints

**Comment by rodislav** [comment]
I'll slow down the video speed, so it'll slightly better, yet, it'll take longer time to watch!

yeah.. english is bad so far.. I mean.. for teaching, is not enough, I'll try to find someone who can help with this.
